server:
  port: 8782
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务器的名称
spring:
  application:
    name: order-service
#ribbon自定义负载均衡策略
product-service:
  ribbon:
    #轮询策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    #随机策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule