server:
  port: 8782
#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#服务器的名称
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
#ribbon自定义负载均衡策略
product-service:
  ribbon:
    #轮询策略
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule
    #随机策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#feign的超时时间设置
feign:
  client:
    config:
      default:
        connectTimeout: 4000
        readTimeout: 4000
  hystrix:
    enabled: true
#hystrix超时时间设置为没有超时
#hystrix:
#  command:
#    default:
#      execution:
#        timeout:
#          enabled: false
#hystrix超时时间设置为4秒
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000